"use client";
import Link from "next/link";
import {FormEvent,useEffect,useRef,useState} from "react";
import {AuthShell} from "@/components/AuthShell";
import {supabase} from "@/lib/supabase";
export default function FinishAccountPage(){
 const [ready,setReady]=useState(false),[invited,setInvited]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState("");const token=useRef("");
 useEffect(()=>{const hash=new URLSearchParams(window.location.hash.slice(1));if(hash.get("type")==="invite"&&hash.get("token_hash")){token.current=hash.get("token_hash")!;setInvited(true);window.history.replaceState(null,"",window.location.pathname);return;}const subscription=supabase.auth.onAuthStateChange((event)=>{if(event==="PASSWORD_RECOVERY")setReady(true);});void supabase.auth.getSession().then(({data})=>{if(data.session)setReady(true);else if(!data.session&&!token.current)setError("This link is missing, expired or already used. Request a new password reset or ask the manager for a new invitation.");});return()=>subscription.data.subscription.unsubscribe();},[]);
 async function activate(){setBusy(true);setError("");try{const result=await supabase.auth.verifyOtp({token_hash:token.current,type:"invite"});if(result.error)throw result.error;token.current="";setInvited(false);setReady(true);}catch{setError("This invitation is expired or already used. Ask your manager for a new invitation, or reset your password if you already activated your account.");}finally{setBusy(false);}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const password=String(form.get("password"));if(password!==form.get("confirm")){setError("The passwords do not match.");return;}setBusy(true);setError("");try{const result=await supabase.auth.updateUser({password});if(result.error)throw result.error;const signedOut=await supabase.auth.signOut({scope:"local"});if(signedOut.error)throw signedOut.error;setReady(false);setDone(true);}catch(e){setError(e instanceof Error?e.message:"Unable to save your password.");}finally{setBusy(false);}}
 return <AuthShell eyebrow="Private team access" title={done?"Password saved":"Set your password"}>{invited?<><p className="text-sm text-neutral-600">Activate the team invitation for your email, then choose your own password.</p><button className="btn btn-primary mt-5" disabled={busy} onClick={()=>void activate()}>{busy?"Activating…":"Activate my invitation"}</button></>:null}{ready?<form onSubmit={submit}><label className="field-label" htmlFor="new-password">New password</label><input id="new-password" name="password" type="password" autoComplete="new-password" minLength={12} className="field" required/><p className="mt-2 text-xs text-neutral-600">Use at least 12 characters.</p><label className="field-label mt-5" htmlFor="confirm-password">Confirm password</label><input id="confirm-password" name="confirm" type="password" autoComplete="new-password" minLength={12} className="field" required/><button className="btn btn-primary mt-5" disabled={busy}>{busy?"Saving…":"Save password"}</button></form>:null}{done?<p role="status" className="notice">Sign in with your new password. Managers still need MFA. Parents can request a child link after signing in.</p>:null}{error?<p role="alert" className="notice mt-5">{error}</p>:null}<div className="mt-6 flex flex-wrap gap-4 text-sm font-bold underline"><Link href="/login">Sign in</Link><Link href="/reset-password">Request another reset</Link></div></AuthShell>;
}

