"use client";
import {FormEvent,useState} from "react";
import {authedFetch,endpoints} from "@/lib/api";
import {requireManager} from "@/lib/management-access";
export function ParentInvitation(){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[link,setLink]=useState(""),[accountId,setAccountId]=useState("");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError("");setLink("");setMessage("");setAccountId("");try{await requireManager();const result=await authedFetch<{message:string;activation_url?:string;account_id:string}>(endpoints.parentOnboarding,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),full_name:form.get("full_name")})});setMessage(result.message);setLink(result.activation_url||"");setAccountId(result.account_id);}catch(e){setError(e instanceof Error?e.message:"Unable to prepare parent invitation.");}finally{setBusy(false);}}
 return <section className="card mt-6 p-6"><h2 className="text-xl font-bold">Activate a parent account</h2><p className="mt-3 text-sm text-neutral-600">Prepare a parent login, then share its private activation link directly with that parent. Existing accounts use sign-in or password recovery. Family Links controls which child they can access.</p><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="field-label" htmlFor="parent-invite-name">Parent name</label><input id="parent-invite-name" name="full_name" className="field" maxLength={100} required disabled={busy}/></div><div><label className="field-label" htmlFor="parent-invite-email">Parent email</label><input id="parent-invite-email" name="email" type="email" className="field" maxLength={254} required disabled={busy}/></div><button className="btn btn-primary justify-self-start" disabled={busy}>{busy?"Preparing…":"Prepare parent activation"}</button></form>{error?<p className="notice mt-4" role="alert">{error}</p>:null}{message?<p className="notice mt-4" role="status">{message}</p>:null}{accountId?<p className="mt-3 break-all text-sm">Account ID for Family Links: {accountId}</p>:null}{link?<><label htmlFor="parent-activation-link" className="field-label mt-4">Private activation link — share only with this parent</label><textarea id="parent-activation-link" className="field min-h-24" readOnly value={link}/><p className="mt-2 text-xs text-neutral-600">Treat this link like a password. It is single-use and expires according to the team’s authentication settings. This page does not store the link.</p></>:null}</section>;
}

