"use client";
import {useEffect,useRef,useState} from 'react';
export function PlayerPhotoCrop({onReady}:{onReady:(file:File|null)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null);const [image,setImage]=useState<HTMLImageElement|null>(null);const [url,setUrl]=useState('');const [zoom,setZoom]=useState(1);const [x,setX]=useState(50);const [y,setY]=useState(50);const [error,setError]=useState('');
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
 useEffect(()=>{if(!image||!canvas.current)return;const c=canvas.current;const ctx=c.getContext('2d');if(!ctx)return;const size=Math.min(image.naturalWidth,image.naturalHeight)/zoom;const sx=(image.naturalWidth-size)*x/100;const sy=(image.naturalHeight-size)*y/100;ctx.clearRect(0,0,512,512);ctx.drawImage(image,sx,sy,size,size,0,0,512,512);onReady(null);},[image,zoom,x,y,onReady]);
 async function select(file?:File){onReady(null);setError('');setImage(null);if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setError('Choose a JPEG, PNG or WebP up to 8 MB.');return;}const next=URL.createObjectURL(file);setUrl(next);const img=new Image();img.onload=()=>{setZoom(1);setX(50);setY(50);setImage(img);};img.onerror=()=>setError('Unable to open this image.');img.src=next;}
 return <div className="rounded-xl border p-4"><label className="field-label" htmlFor="roster-photo">Choose roster photo</label><input id="roster-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void select(event.target.files?.[0])} className="block w-full max-w-full text-sm"/>{error?<p role="alert">{error}</p>:null}{image?<><canvas ref={canvas} width={512} height={512} className="mx-auto my-4 aspect-square w-full max-w-60 rounded-full" aria-label="Cropped photo preview"/>{[['Zoom',zoom,setZoom,1,3,.05],['Horizontal crop',x,setX,0,100,1],['Vertical crop',y,setY,0,100,1]].map(([label,value,set,min,max,step])=><label key={String(label)} className="my-3 block text-sm font-bold">{String(label)}<input className="block w-full" type="range" min={Number(min)} max={Number(max)} step={Number(step)} value={Number(value)} onChange={event=>(set as (v:number)=>void)(Number(event.target.value))}/></label>)}<button type="button" className="btn btn-outline" onClick={()=>canvas.current?.toBlob(blob=>{if(blob)onReady(new File([blob],'roster-portrait.jpg',{type:'image/jpeg'}));},'image/jpeg',.9)}>Use this crop</button><p className="mt-2 text-xs text-neutral-500">Check the preview, then select “Use this crop”. Photos are processed again to remove location metadata.</p></>:null}</div>;
}
