"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,X} from "lucide-react";
import {openProcessedImage} from "@/lib/private-media";
type Photo=Record<string,unknown>;
function Thumbnail({photo}:{photo:Photo}){
 const host=useRef<HTMLDivElement>(null);const [url,setUrl]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let live=true,objectUrl="",started=false;const observer=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting)||started)return;started=true;observer.disconnect();void openProcessedImage(String(photo.thumbnail_path||photo.processed_private_path||"")).then(value=>{objectUrl=value;if(live)setUrl(value);else URL.revokeObjectURL(value);}).catch(()=>{if(live)setError("Preview unavailable");});},{rootMargin:"200px"});if(host.current)observer.observe(host.current);return()=>{live=false;observer.disconnect();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[photo.thumbnail_path,photo.processed_private_path]);
 return <div ref={host} className="grid aspect-[4/3] place-items-center overflow-hidden bg-neutral-100">{url&&!error?<img src={url} alt={String(photo.caption||"Private team photo")} className="h-full w-full object-cover" onError={()=>setError("Preview unavailable")}/>:<span className="grid place-items-center gap-2 text-sm text-neutral-500"><Camera size={28}/>{error||"Loading preview…"}</span>}</div>;
}
export function PrivateGallery({photos}:{photos:Photo[]}){
 const [search,setSearch]=useState(""),[status,setStatus]=useState("all"),[page,setPage]=useState(0),[selected,setSelected]=useState<Photo|null>(null),[url,setUrl]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),objectUrl=useRef(""),request=useRef(0);
 useEffect(()=>()=>{request.current++;if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);},[]);
 const filtered=photos.filter(p=>(status==="all"||p.status===status)&&String(p.caption||"").toLowerCase().includes(search.toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/12));const current=Math.min(page,pages-1);
 async function open(photo:Photo){const currentRequest=++request.current;setSelected(photo);setError("");setUrl("");setLoading(true);if(objectUrl.current){URL.revokeObjectURL(objectUrl.current);objectUrl.current="";}dialog.current?.showModal();try{const result=await openProcessedImage(String(photo.processed_private_path||photo.thumbnail_path||""));if(currentRequest!==request.current){URL.revokeObjectURL(result);return;}objectUrl.current=result;setUrl(result);}catch{if(currentRequest!==request.current)return;setError("This photo could not be opened. Refresh or ask the uploader to submit it again.");}finally{if(currentRequest===request.current)setLoading(false);}}
 function close(){request.current++;setLoading(false);dialog.current?.close();setSelected(null);setUrl("");if(objectUrl.current){URL.revokeObjectURL(objectUrl.current);objectUrl.current="";}}
 return <><div className="flex flex-wrap items-end gap-3"><div className="min-w-48 flex-1"><label className="field-label" htmlFor="photo-search">Search photo captions</label><input id="photo-search" className="field" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></div><div><label className="field-label" htmlFor="photo-status">Review status</label><select id="photo-status" className="field" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}>{["all","approved","pending","rejected"].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></div></div><p className="text-sm text-neutral-600" role="status">{filtered.length} accessible photos from the latest 50 uploads. Pending uploads are visible to their uploader and authorized reviewers.</p><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.slice(current*12,current*12+12).map(photo=><article key={String(photo.id)} className="card overflow-hidden"><Thumbnail photo={photo}/><div className="p-4"><span className={"rounded-full px-2 py-1 text-xs font-bold "+(photo.status==="approved"?"bg-green-50 text-green-800":photo.status==="rejected"?"bg-red-50 text-red-800":"bg-amber-50 text-amber-900")}>{String(photo.status||"pending")}</span><h2 className="mt-3 font-bold">{String(photo.caption||"Team photo")}</h2><p className="mt-1 text-xs text-neutral-500">{photo.created_at?new Date(String(photo.created_at)).toLocaleDateString("en-CA",{timeZone:"America/Toronto"}):""}</p><button className="btn btn-light mt-3" onClick={()=>void open(photo)}>Open Photo</button></div></article>)}</div>{!filtered.length?<p className="notice">No photos match these filters.</p>:null}{pages>1?<nav aria-label="Photo pages" className="flex items-center gap-3"><button className="btn btn-light" disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} of {pages}</span><button className="btn btn-light" disabled={current===pages-1} onClick={()=>setPage(current+1)}>Next</button></nav>:null}<dialog ref={dialog} className="private-photo-dialog" aria-label="Private photo viewer" onCancel={close}><div className="flex items-center justify-between gap-3"><h2 className="font-bold">{String(selected?.caption||"Private photo")}</h2><button className="btn btn-light !px-3" aria-label="Close photo" onClick={close}><X size={20}/></button></div>{loading?<p className="mt-5" role="status">Opening private photo…</p>:null}{error?<p role="alert" className="notice mt-5">{error}</p>:null}{url?<img src={url} alt={String(selected?.caption||"Private team photo")} className="mt-5 max-h-[70dvh] w-full object-contain" onError={()=>setError("This stored image is damaged. Ask the uploader to submit a new photo.")}/>:null}</dialog></>;
}

