"use client";
import {RosterAvatar} from "./RosterAvatar";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {getRoster,RosterPlayer,RosterSnapshot,rosterPhoto} from '@/lib/roster-api';
import {supabase} from '@/lib/supabase';
import {PlayerKitCard} from './PlayerKitCard';
import {InteractiveField} from './InteractiveField';
import {RosterPlayerEditor} from './RosterPlayerEditor';
export function RosterProfiles(){
 const [data,setData]=useState<RosterSnapshot|null>(null);const [error,setError]=useState('');const [editor,setEditor]=useState<RosterPlayer|null>(null);
 async function refresh(){try{const user=await supabase.auth.getUser();let snapshot=await getRoster(false);if(user.data.user){try{snapshot=await getRoster(true);}catch{/* Public roster remains available; private controls require verified access. */}}setData(snapshot);setError('');}catch(err){setError(err instanceof Error?err.message:'Unable to load roster');}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},15000);const onFocus=()=>void refresh();window.addEventListener('focus',onFocus);const {data:auth}=supabase.auth.onAuthStateChange(()=>{setData(null);setTimeout(()=>void refresh(),0);});return()=>{clearInterval(timer);window.removeEventListener('focus',onFocus);auth.subscription.unsubscribe();};},[]);
 const players=data?.players.filter(p=>p.active)??[];
 return <><section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black uppercase">Player Profiles</h2>{data?.manager?<Link className="btn btn-outline" href="/admin/players">Manage Roster</Link>:null}</div><p className="mb-5 text-sm text-neutral-600">Approved first names, current numbers and developing positions. Kit illustrations are generic; real portraits appear only after guardian consent and manager review.</p>{error?<div role="alert" className="notice">{error}<button className="ml-3 underline" onClick={()=>void refresh()}>Retry</button></div>:!data?<p role="status" className="card p-6">Loading player profiles…</p>:!players.length?<div className="card p-6"><h3 className="font-black">Player profiles are awaiting publication</h3><p className="mt-2 text-sm text-neutral-600">Families can link their child in My Players. A manager publishes each profile after the guardian’s consent is recorded.</p><Link href="/portal/players" className="btn btn-primary mt-4">My Players</Link></div>:<div className="grid grid-cols-2 gap-4 md:grid-cols-3">{players.map(player=><div key={player.id} className="min-w-0">{player.photo_id?<article className="card overflow-hidden"><RosterAvatar id={player.photo_id} name={player.name} className="aspect-[26/35] w-full object-cover"/><div className="p-4"><h3 className="break-words text-xl font-black uppercase">{player.name}</h3><p className="mt-2 text-sm">{player.number===null?'Number pending':'#'+player.number}</p></div></article>:<PlayerKitCard name={player.name} number={player.number}/>}<p className="mt-2 text-sm text-neutral-600">{player.position||'Positions rotating'}</p>{player.can_edit?<button className="btn btn-outline mt-2 w-full" onClick={()=>setEditor(player)}>{data?.manager?'Edit Player':'Edit My Player'}</button>:null}</div>)}</div>}</section><InteractiveField players={players.filter(p=>p.public_visible&&p.name_consent)} formation={data?.formation.name||'1-3-2-1'} showNames={data?.formation.show_names}/>{editor&&data?<RosterPlayerEditor player={editor} manager={data.manager} onClose={()=>setEditor(null)} onSaved={()=>void refresh()}/>:null}</>;
}
