"use client";
import {FormEvent,useEffect,useState} from 'react';
import {authedFetch,endpoints} from '@/lib/api';
import {supabase} from '@/lib/supabase';
type User={id:string;email:string;name:string|null;roles:string[];confirmed_at:string|null;last_sign_in_at:string|null;mfa_enabled:boolean};
type Invite={id:string;email:string;role:string;status:string;expires_at:string;name:string|null};
const roles=['parent_player','manager','admin','photographer','sponsor'];
const label=(r:string)=>({parent_player:'Parent / Player',manager:'Manager',admin:'Administrator',photographer:'Photographer',sponsor:'Sponsor'}[r]||r);
type Result={users?:User[];invites?:Invite[];message?:string;activation_url?:string};
export function UserManagement(){
 const [available,setAvailable]=useState(false),[self,setSelf]=useState(''),[users,setUsers]=useState<User[]>([]),[invites,setInvites]=useState<Invite[]>([]),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[link,setLink]=useState(''),[drafts,setDrafts]=useState<Record<string,string>>({});
 async function load(){const r=await authedFetch<Result>(endpoints.userManagement,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'list'})});setUsers(r.users||[]);setInvites(r.invites||[]);}
 useEffect(()=>{void(async()=>{const s=await supabase.auth.getSession();const id=s.data.session?.user.id;if(!id)return;const r=await supabase.from('user_roles').select('role').eq('user_id',id);if(r.data?.some(x=>x.role==='admin')){setSelf(id);setAvailable(true);try{await load();}catch(e){setError(e instanceof Error?e.message:'Unable to load users');}}})();},[]);
 async function act(action:string,input:Record<string,unknown>){setBusy(true);setMessage('');setError('');setLink('');try{const r=await authedFetch<Result>(endpoints.userManagement,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,input})});setMessage(r.message||'Account updated.');setLink(r.activation_url||'');await load();return true;}catch(e){setError(e instanceof Error?e.message:'Unable to update account');return false;}finally{setBusy(false);}}
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);if(await act('invite',{email:d.get('email'),full_name:d.get('full_name'),role:d.get('role')}))f.reset();}
 if(!available)return null;
 return <section id="users" className="card mt-8 p-6"><h2 className="text-2xl font-black uppercase">Users &amp; Invitations</h2><p className="mt-3 text-sm text-neutral-600">Administrator access with MFA. Role changes replace the account’s current roles. Family links remain separate and must be verified before a parent can see a child.</p>
 <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={invite}><div><label htmlFor="account-email" className="field-label">Email</label><input id="account-email" name="email" type="email" className="field" required maxLength={254}/></div><div><label htmlFor="account-name" className="field-label">Name (optional)</label><input id="account-name" name="full_name" className="field" maxLength={140}/></div><div><label htmlFor="account-role" className="field-label">Access role</label><select id="account-role" name="role" className="field">{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select></div><button disabled={busy} className="btn btn-primary self-end">{busy?'Working…':'Send invitation'}</button></form>
 {message?<p role="status" className="notice mt-4">{message}</p>:null}{error?<p role="alert" className="notice mt-4">{error}</p>:null}{link?<div className="mt-4"><label htmlFor="account-activation" className="field-label">Private activation link — share only with the recipient</label><textarea id="account-activation" readOnly className="field" value={link}/><p className="text-xs mt-2">Single-use, expires under the authentication settings. This page does not save the link.</p></div>:null}
 <div className="mt-8 flex flex-wrap items-end gap-4"><h3 className="text-xl font-bold">Registered users ({users.length})</h3><button type="button" className="btn" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh</button></div><label className="field-label mt-4" htmlFor="user-search">Search name or email</label><input id="user-search" className="field" value={search} onChange={e=>setSearch(e.target.value)}/>
 <div className="mt-4 grid gap-4">{users.filter(u=>(u.email+' '+u.name).toLowerCase().includes(search.toLowerCase())).map(u=><article key={u.id} className="rounded-xl border border-neutral-200 p-4"><h4 className="font-bold break-all">{u.name||u.email}{u.id===self?' (you)':''}</h4><p className="text-sm break-all">{u.email}</p><p className="mt-2 text-sm">{u.confirmed_at?'Activated':'Awaiting activation'} · MFA {u.mfa_enabled?'enabled':'not enrolled'} · Current access: {u.roles.map(label).join(', ')||'No team role'}</p><p className="text-xs mt-1">Last sign-in: {u.last_sign_in_at?new Date(u.last_sign_in_at).toLocaleString():'Never'}</p><div className="mt-3 flex flex-wrap gap-3"><select aria-label={'Role for '+u.email} className="field max-w-xs" disabled={busy||u.id===self} value={drafts[u.id]||u.roles[0]||'parent_player'} onChange={e=>setDrafts({...drafts,[u.id]:e.target.value})}>{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select><button className="btn" disabled={busy||u.id===self||!drafts[u.id]} onClick={()=>{if(window.confirm('Replace all current roles for '+u.email+' with '+label(drafts[u.id])+'?'))void act('role',{user_id:u.id,role:drafts[u.id]});}}>Save role</button>{!u.confirmed_at?<button className="btn" disabled={busy} onClick={()=>void act('resend',{user_id:u.id})}>Resend activation</button>:<a href="/reset-password" className="text-sm underline self-center">Password recovery page</a>}</div></article>)}</div>
 <h3 className="mt-8 text-xl font-bold">Invitation history</h3><div className="mt-4 grid gap-3">{invites.map(i=><article key={i.id} className="rounded-xl border p-4"><p className="font-bold break-all">{i.email}</p><p className="text-sm">{label(i.role)} · {i.status} · Expires {new Date(i.expires_at).toLocaleDateString()}</p>{['pending','expired'].includes(i.status)?<div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} className="btn" onClick={()=>void act('invite',{email:i.email,full_name:i.name||'',role:i.role})}>Send / resend invitation</button>{i.status==='pending'?<button disabled={busy} className="btn" onClick={()=>{if(window.confirm('Cancel the pending invitation for '+i.email+'?'))void act('cancel',{id:i.id});}}>Cancel invitation</button>:null}</div>:null}</article>)}{!invites.length?<p>No invitations yet.</p>:null}</div></section>;
}
