"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {WeekView} from "@/components/PortalSchedule";
import {PortalHeader} from "@/components/PortalHeader";
import {ChildLinkRequest} from "@/components/ChildLinkRequest";
import {EventDetails,TeamEvent} from "@/components/EventDetails";
import {parentTasks} from "@/lib/parent-tasks";
import {authedFetch,endpoints} from "@/lib/api";
import {supabase} from "@/lib/supabase";
type Dashboard={user:{id:string;email:string|null};profile:{display_name?:string|null;full_name?:string|null}|null;roles:string[];players:{id:string;first_name:string;last_name:string;jersey_number:number|null}[];events:TeamEvent[];attendance:{event_id:string;player_id:string;status:string}[];kit_orders:{payment_status:string}[];announcements:{id:string;title:string;body:string}[];team_links:{link_key:string;label:string;url:string}[];};
export default function PortalPage(){
 const router=useRouter();const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError("");try{const d=await authedFetch<Dashboard>(endpoints.parentDashboard);if(!d.roles.some(r=>["parent_player","manager","admin","photographer"].includes(r)))throw new Error("This account does not have team portal access. Contact the manager.");if(d.roles.some(r=>["admin","manager"].includes(r))){const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error)throw aal.error;if(aal.data.currentLevel!=="aal2"){router.replace("/mfa");return;}}setData(d);}catch(e){const message=e instanceof Error?e.message:"Unable to load your portal.";setError(message);if(message==="Please sign in.")router.replace("/login");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const tasks=data?parentTasks(data):null;const nextEvent=data?.events.find(e=>e.id===tasks?.nextEvent?.id);
 return <div className="min-h-screen bg-neutral-100"><PortalHeader title="Family Dashboard"/><main id="portal-main" className="container py-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-red-600">Your team, this week</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Welcome, {data?.profile?.display_name||data?.profile?.full_name||"parent"}</h1><p className="mt-2 text-neutral-600">Your children, next session and things that need a reply.</p></div><button className="btn btn-light" onClick={()=>void load()} disabled={loading}>{loading?"Loading…":"Refresh"}</button></div>{error?<p role="alert" className="notice mt-5">{error}</p>:null}{!data?<p className="notice mt-6">{loading?"Loading your team information…":"Use Refresh to retry."}</p>:<>
 <div className="mt-6 grid gap-5 xl:grid-cols-[1.4fr_1fr]"><section className="card p-6"><h2 className="font-bold text-red-600">Next session</h2>{nextEvent?<><h3 className="mt-4 text-2xl font-bold">{nextEvent.title}</h3><EventDetails event={nextEvent}/><Link className="btn btn-primary mt-5" href="/portal/activity/attendance">View session & reply</Link></>:<p className="mt-4 text-neutral-600">No upcoming session has been posted. Check Spond for the latest team invitation.</p>}</section><section className="card p-6"><h2 className="text-xl font-bold">Needs your attention</h2><div className="mt-4 grid gap-3">{!data.players.length?<Link href="#my-children" className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-bold">Link your child</p><p className="mt-1 text-sm">The manager verifies family access to an existing squad player.</p></Link>:null}<Link href="/portal/activity/attendance" className="rounded-xl border p-4 hover:border-red-500"><p className="font-bold">{tasks?.attendanceReplies||0} attendance replies needed</p><p className="mt-1 text-sm text-neutral-600">For your children’s sessions in the next seven days.</p></Link><Link href="/portal/activity/payments" className="rounded-xl border p-4 hover:border-red-500"><p className="font-bold">{tasks?.ordersToReview||0} kit orders awaiting full payment</p><p className="mt-1 text-sm text-neutral-600">Review the manager’s recorded status.</p></Link></div><Link href="/portal/tools#consent" className="mt-4 block text-sm font-bold text-red-700 underline">Review forms & consent</Link></section></div>
 <WeekView events={data.events}/><Link href="/portal/training" className="btn btn-primary">Training & Development</Link>
 <section id="family-children" className="mt-6 scroll-mt-28"><h2 className="text-xl font-bold">My children</h2>{data.players.length?<ul className="mt-4 grid gap-3 sm:grid-cols-2" aria-label="Linked children">{data.players.map(p=><li key={p.id} className="card flex items-center justify-between gap-3 p-5"><div><p className="font-bold">{p.first_name} {p.last_name}{p.jersey_number!==null?<span className="ml-2 text-neutral-500">#{p.jersey_number}</span>:null}</p><p className="mt-1 text-sm text-green-700">Family access linked</p></div><Link href="/portal/tools#consent" className="text-sm font-bold text-red-700 underline">Forms</Link></li>)}</ul>:<p className="notice mt-4">No child is linked yet. After manager approval, refresh this page to see your child.</p>}<ChildLinkRequest accountId={data.user.id}/></section>
 <div className="mt-6 grid gap-5 xl:grid-cols-2"><section className="card p-6"><h2 className="text-xl font-bold">Team updates</h2>{data.announcements.length?data.announcements.slice(0,5).map(a=><article key={a.id} className="mt-4 border-t pt-4"><h3 className="font-bold">{a.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-neutral-600">{a.body}</p></article>):<p className="mt-4 text-sm text-neutral-600">No team announcements yet.</p>}</section><section className="card p-6"><h2 className="text-xl font-bold">Quick links</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["/portal/activity/duties","Game duties"],["/portal/activity/media","Private team photos"],["/portal/activity/carpool","Carpool board"],["/portal/activity/account","My account"],["/portal/activity/sisterhood","Recognize a teammate"],["/portal/tools","All parent tools"]].map(([href,label])=><Link key={href} href={href} className="rounded-xl border p-3 text-sm font-bold hover:border-red-500">{label}</Link>)}</div>{data.team_links?.filter(l=>["spond_group","spond_web"].includes(l.link_key)).map(l=><a key={l.link_key} href={l.url} target="_blank" rel="noopener noreferrer" className="mt-4 block text-sm font-bold text-red-700 underline">{l.label} ↗</a>)}</section></div>{data.roles.some(r=>["manager","admin"].includes(r))?<Link href="/admin" className="btn btn-light mt-6">Open management dashboard</Link>:null}</>}</main></div>;
}

