const assert=require('node:assert/strict');
const ts=require('typescript');const fs=require('node:fs');const Module=require('node:module');
const filename=require('node:path').resolve('lib/team-finance.ts');const mod=new Module(filename,module);
mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
const {financeTotals,statementDifference,budgetSpent,parseCents,csvCell}=mod.exports;
const lines=[{id:'a',planned_cents:10000},{id:'b',planned_cents:5000}];
const settings={opening_cents:0,opening_date:'2026-10-03'};
const t=(kind,cents,date='2026-10-03',extra={})=>({kind,amount_cents:cents,occurred_on:date,budget_line_id:'a',voided_at:null,...extra});
const transactions=[t('income',10000),t('expense',2500),t('expense_refund',500),t('income_refund',1000),t('expense',9000,'2026-10-04',{voided_at:'today'}),t('income',1000,'2026-10-05')];
assert.deepEqual(financeTotals(lines,transactions,settings),{planned:15000,spent:2000,received:10000,remaining:13000,balance:8000});
assert.equal(budgetSpent('a',transactions),2000);
assert.equal(financeTotals(lines,transactions,{opening_cents:null,opening_date:null}).balance,null);
assert.equal(financeTotals(lines,[...transactions,t('income',10000,'2026-10-01')],settings).balance,8000);
assert.equal(statementDifference({kind:'statement',closing_cents:7000,period_end:'2026-10-03'},transactions,settings),0);
assert.equal(statementDifference({kind:'statement',closing_cents:7200,period_end:'2026-10-03'},transactions,settings),200);
assert.equal(statementDifference({kind:'statement',closing_cents:0,period_end:'2026-10-01'},transactions,settings),null);
assert.equal(parseCents('930.60'),93060);assert.equal(parseCents('0'),0);assert.equal(parseCents('-1.01',true),-101);
for(const invalid of ['1.001','NaN','-1','1e2','1000000.01',''])assert.throws(()=>parseCents(invalid));
assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('quoted "text"'),'"quoted ""text"""');
console.log('Finance calculations passed: integer cents, refunds, voids, opening dates, statement reconciliation and safe CSV.');
